name: depthmaps
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - tensorflow=1.3.0
  - h5py=2.7.0
  - numpy=1.12.1
  - pillow=4.2.1
  - scipy=0.19.1
  - scikit-learn=0.19.0
  - matplotlib>=2.0.2
  - pip
  - pip:
    - tensorflow-tensorboard>=0.1.5
