---
title: Depth Estimation using Generative Adversarial Networks
author:
  - Nina Wiedermann
  - Alexander Höreth
institute: Institute of Cognitive Science, University of Osnabrück
date: 30.09.2017
...
