---
title: Depth Estimation using Generative Adversarial Networks
author:
  - Alexander Höreth
  - Nina Wiedemann
  - Robin Weiss
institute: Institute of Cognitive Science, University of Osnabrück
date: 30.09.2017
codeBlockCaptions: True
figPrefix:
  - figure
  - figures
lstPrefix:
  - listing
  - listings
secPrefix:
  - section
  - sections
...
